# Generated by Django 4.1.7 on 2023-03-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='estadodelete',
        ),
    ]
